- name: install nodesource.com package via specific setup script
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - 

- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - nodejs


- name: symlink nodejs to node
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: install local.hex package manager
  sudo_user: vagrant
  sudo: yes
  shell: mix local.hex --force
  args:
    creates: /home/vagrant/.mix/archives/hex.ez


- name: install phoenix
  sudo_user: vagrant
  sudo: yes
  shell: mix archive.install {{phoenix_version_url}} --force
  args:
    creates: /home/vagrant/.mix/archives/{{phoenix_version}}
