---
- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
  # postgresql package requires correct locale when installing
  environment:
    LC_ALL: en_US.UTF-8

    
- name: ensure postgresql is running
  service: name=postgresql state=running enabled=yes

# Ensure that postgresql is restarted before we create databases and users
- meta: flush_handlers

- name: Create PG User
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} state=present 
- name: Create Database
  sudo_user: postgres
  postgresql_db: name={{ db_name }} owner={{ db_user }}

- name: Provide user with DB permissions
  sudo_user: postgres
  postgresql_user: user={{ db_user }} db={{ db_name }} priv=ALL

- name: Restart Postgres
  service: name=postgresql state=restarted
